### ISSUE TITLE
Enable Bleach correction in headless

### ISSUE THREAD

**Issue by lldelisle** [fiji/CorrectBleach#3]
Dear developpers,
Would it be possible to make this line optional so Bleach correction can be used in headless mode?

https://github.com/fiji/CorrectBleach/blob/69adfb39574f85ea1398ec0cccf0d53003dad476/src/main/java/emblcmci/BleachCorrection_ExpoFit.java#L88

Thank you in advance

**Comment by lldelisle** [comment]
If you are interested I can write a PR.

**Comment by miura** [comment]
Hi @lldelisle 
 Great idea, pls PR!

**Comment by lldelisle** [comment]
How can I test if my PR is working? I mean how can I tell Fiji to use my version instead of the built-in one?

**Comment by miura** [comment]
Replace the plugin in your local Fiji with the plugin you modified/compiled by yourself, and then test locally.

**Comment by lldelisle** [comment]
Sorry, how do I compile my local version? (I found the jar to replace)

**Comment by miura** [comment]
This project uses the build tool maven, so just use it to compile the code. 
If you do not have maven installed, please do so. then in the project folder:

`mvn package`

This command compiles and generates a jar file under `target/`.

For debugging errors, I usually use:

`mvn clean compile`

When this becomes successful without error, I package the compiled code into a jar file using the first command. 

For more details about maven, see here:
[ImageJ Wiki Maven](https://imagej.net/develop/maven)

**Comment by lldelisle** [comment]
Thanks

**Comment by miura** [comment]
great, I will test it.

**Comment by miura** [comment]
Hi @lldelisle 

I tested and it went successfully. 
As this is a good chance to power up the "headless mode", I made some additional upgrades on top of yours:

- GUI environment detection also with 3D time series (it was only with 2D time series that you made the change)
- adding more flexibility to use it from scripts
- enable "headless mode", regardless of the presence of the GUI environment, by scripting.

Could you compile and test if it works in the way you are using?  
The code is existing in a branch called `expmethod_headless`. 
[fiji/CorrectBleach/tree/expmethod_headless](fiji/CorrectBleach/tree/expmethod_headless)

If this is OK with you, I will merge these changes. 

An example of usage with Jython is here:
https://gist.github.com/miura/9080feb52eb74079ae393dd9320cb6ed

Thanks, 
Kota

**Comment by lldelisle** [comment]
Hi @miura ,
I tested your branch and this worked perfectly for me.
Thanks

**Comment by miura** [comment]
OK, now the changes are in the master branch.

**Comment by lldelisle** [comment]
Thanks @miura what is the usual process, how do you release? I think it is part of the plugins provided by Fiji downloads. Do you know when it will be packed into a Fiji build? (I am using it within conda and we build our conda recipe on the archive links, see https://github.com/bioconda/bioconda-recipes/blob/c58332f9792fe82f25de9732bb40e921d35fc7e6/recipes/fiji/meta.yaml#L6-L9 ). As soon as a new build of Fiji incorporate these changes I will update the conda recipe.

**Comment by imagejan** [comment]
@lldelisle getting this fix into a Fiji release involves the following steps:

* cutting and deploying a `2.0.4` release of this repository (using `release-version.sh` from `scijava-scripts`); I'll be happy to do that if you agree, @miura (maybe after checking my suggestion in #7 as well).
* updating the version in `pom-scijava` here: https://github.com/scijava/pom-scijava/blob/cb2c285078c5056625550f6152dbb0665097125f/pom.xml#L720
* waiting for the next releases of `org.scijava:pom-scijava` and `sc.fiji:fiji` (as far as I can tell, @ctrueden is planning this within the next 2(?) weeks).

**Comment by lldelisle** [comment]
Thanks for the info. Could you have a look at #6 , if I am right, would be good to include the fix.

**Comment by miura** [comment]
@lldelisle , @imagejan 

OK, I will work on #6 and also test #7 - before the next Fiji release. 

Thanks a lot!
Kota

**Comment by lldelisle** [comment]
Thank you so much.

**Comment by lldelisle** [comment]
Hi,
Any update on a Fiji release that would incorporate these changes?

**Comment by imagejan** [comment]
It seems version 2.1.0 was not released?! This commit bumps the version: https://github.com/fiji/CorrectBleach/commit/e9f49512c3be4b9e2f9cfd0a04c680f342f03855, but there's no [tag](https://github.com/fiji/CorrectBleach/tags) for the release version.

@miura it seems you didn't use `release-version.sh` from [`scijava-scripts`](https://github.com/scijava/scijava-scripts) to cut the release.

Once we have a release, we need to update the managed version of `CorrectBleach` in `pom-scijava` here:
https://github.com/scijava/pom-scijava/blob/89a215fb3daeca6785260fedeab2bfb0296ee2a7/pom.xml#L720

It this happens before the `pom-scijava-34.0.0` release that @ctrueden is planning any time now, the fixes will be on the Java-8 update site and shipped with an up-to-date Fiji.

@miura let me know if you need help cutting the release, I can do it for you.

**Comment by ctrueden** [comment]
I am cutting the release of CorrectBleach 2.1.0 now, and will update pom-scijava as well. The pom-scijava 34 release is very close now. Probably today or tomorrow.

**Comment by miura** [comment]
Hi @ctrueden , Thanks a lot for cutting the release for the updated CorrectBleach! - and to @imagejan for offering to help me.

**Comment by lldelisle** [comment]
Hi there,
It seems that there was a fiji release: https://github.com/fiji/fiji/tags, however, I don't understand the relationship between the tags in the fiji depo and the zip files provided here: https://downloads.imagej.net/fiji/archive/, could you explain it to me please?

**Comment by ctrueden** [comment]
@lldelisle I saw the issue you filed at fiji/fiji#321; sorry for the slow reply, I will respond there.

**Comment by lldelisle** [comment]
No problem I just wanted to be sure you saw it. Thank you very much for all you did for me.
