### ISSUE TITLE
Exponential fit question

### ISSUE THREAD

**Issue by lldelisle** [fiji/CorrectBleach#6]
Hi,
Reading the formula, I feel like it is not correct (but maybe I did not understood fully).
https://github.com/fiji/CorrectBleach/blob/a3934322a0d409ab18a728130843138fa1672614/src/main/java/emblcmci/BleachCorrection_ExpoFit.java#L213-L214

The fit was done on the stacks ids in x (0-based), see: 
https://github.com/fiji/CorrectBleach/blob/a3934322a0d409ab18a728130843138fa1672614/src/main/java/emblcmci/BleachCorrection_ExpoFit.java#L77

But it seems that the factor is evaluated on the number of tacks, 1-based in the formula above.
For example when `i` is 0. The factor should be 1 but it is not.

If I understood correctly, please, tell me I can make a PR.

**Comment by miura** [comment]
Hi @lldelisle 

Thanks a lot for your suggestion!

I just now looked at it and you are most likely correct, that the ratio computation is frame-shifted by 1 in the exponential fitting method and this should be fixed.  

Not really related to this but
> For example when i is 0. The factor should be 1 but it is not.

I remember that the factor at the 0th frame can also become a value other than 1.0 in the case of the exponential fitting, as the estimate at the 0th frame based on the fitted formula can have a value other than the original.  

In any case, I will fix the code and test it with some examples and come back to you. 

Again, I appreciate your careful code reading and the suggestion!
Cheers, 
Kota

**Comment by lldelisle** [comment]
I think the factor must be 1.0 but the mean value may be different from `calcExponentialOffset(res_a, res_b, res_c, 0.0)` as indeed the estimate of the fit may be different from the real value.
By the way, it seems that the fact that the factor is 1.0 in 0 is arbitrary, therefore, do you think it could be meaningful to set as parameter a targeted value (which by default would be the value of the fit in 0) and apply as factor:
```
 ratio = userSetValue 
 		/ calcExponentialOffset(res_a, res_b, res_c, (double) (i + 1)); 
```

**Comment by miura** [comment]
I tested using a synthetic model and added the fix.  see #8 
In the previous code, the correction resulted in the following:

| Original Int | Corrected Int | Ratio              |
|--------------|---------------|--------------------|
| 160.0        | 168.0         | 1.048174656928513  |
| 152.0        | 167.0         | 1.0985065027000687 |
| 145.0        | 167.0         | 1.151076123229251  |
| 139.0        | 168.0         | 1.2059655514512462 |
| 132.0        | 167.0         | 1.263258128471777  |
| 126.0        | 167.0         | 1.3230383445704355 |
| 121.0        | 168.0         | 1.3853916587995578 |
| 115.0        | 167.0         | 1.4504042959499908 |
| 110.0        | 167.0         | 1.5181630197034235 |
| 105.0        | 167.0         | 1.5887548808608498 |
| 100.0        | 166.0         | 1.6622669396307181 |
| 96.0         | 167.0         | 1.7387859610809622 |
| 92.0         | 167.0         | 1.8183980830088373 |

With the fixed version, the correction is shown below. 

| Original Int | Corrected Int | Ratio              |
|--------------|---------------|--------------------|
| 160.0        | 160.0         | 1.0                |
| 152.0        | 159.0         | 1.048174656928513  |
| 145.0        | 159.0         | 1.0985065027000687 |
| 139.0        | 160.0         | 1.151076123229251  |
| 132.0        | 159.0         | 1.2059655514512462 |
| 126.0        | 159.0         | 1.263258128471777  |
| 121.0        | 160.0         | 1.3230383445704355 |
| 115.0        | 159.0         | 1.3853916587995578 |
| 110.0        | 160.0         | 1.4504042959499908 |
| 105.0        | 159.0         | 1.5181630197034235 |
| 100.0        | 159.0         | 1.5887548808608498 |
| 96.0         | 160.0         | 1.6622669396307181 |
| 92.0         | 160.0         | 1.7387859610809622 |

**Comment by miura** [comment]
Hi @lldelisle 

So I fixed and made a new pull request. If you could compile it and check if it is working in your local, it would be great. 

>do you think it could be meaningful to set as a parameter a targeted value (which by default would be the value of the fit in 0) and apply as a factor:

I would say this will just add more parameters to the dialog, and I want to avoid that (less parameter is better). 
What I would do for doing this is not by including a new parameter and setting in the plugin, but after the correction, just multiply the `userSetValue ` as a separate process.

**Comment by lldelisle** [comment]
Hi @miura ,
I tested the PR and it works perfectly. Thank you.
For the `userSetValue`, you are right, the less parameter is better.
